print("Welcome to Band Name Generator!")
city = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
print("Your Band name could be " + city +" " + pet)
input("Press Enter to exit...")
